## 作業：類別平衡切分



### 現實中的分類問題經常遇到類別不均衡的問題。如瑕疵分類，瑕疵樣本通常總是比正常樣本少。

### 請參考範例程式碼Day_034_train_test_split.ipynb試著撰寫程式碼，讓測試集的目標類別能夠均衡分佈。

## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [9]:
len(X[40:])

160

In [16]:
np.where(y==1)[0]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39], dtype=int64)

In [17]:
from sklearn.model_selection import train_test_split

#取類別1
# y1 = y[:40]
# X1 = X[:40]
# X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=10, random_state=42)
# 選出 y 等於 1 的 index 與 y 等於 0 的 index
y1_index = np.where(y==1)[0]
X_train1, X_test1, y_train1, y_test1 = train_test_split(X[y1_index], y[y1_index], test_size=10, random_state=42)

#取類別0
# y0 = y[40:]
# X0 = X[40:]
# X_train0, X_test0, y_train0, y_test0 = train_test_split(X0, y0, test_size=10, random_state=42)
y0_index = np.where(y==0)[0]
X_train0, X_test0, y_train0, y_test0 = train_test_split(X[y0_index], y[y0_index], test_size=10, random_state=42)

#合併
X_test, y_test  = np.concatenate((X_test1, X_test0), axis=0), np.concatenate((y_test1, y_test0), axis=0) 

In [18]:
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [19]:
X_test

array([[ 95,  96,  97,  98,  99],
       [ 80,  81,  82,  83,  84],
       [ 75,  76,  77,  78,  79],
       [130, 131, 132, 133, 134],
       [ 20,  21,  22,  23,  24],
       [ 60,  61,  62,  63,  64],
       [185, 186, 187, 188, 189],
       [135, 136, 137, 138, 139],
       [195, 196, 197, 198, 199],
       [ 30,  31,  32,  33,  34],
       [725, 726, 727, 728, 729],
       [740, 741, 742, 743, 744],
       [905, 906, 907, 908, 909],
       [475, 476, 477, 478, 479],
       [670, 671, 672, 673, 674],
       [345, 346, 347, 348, 349],
       [705, 706, 707, 708, 709],
       [455, 456, 457, 458, 459],
       [700, 701, 702, 703, 704],
       [910, 911, 912, 913, 914]])