In [1]:
import os
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
# 設定 data_path
dir_data = './data/'
f_app_train = os.path.join(dir_data, 'DS_train.csv')
f_app_train_label = os.path.join(dir_data, 'DS_trainLabels.csv')
f_app_test = os.path.join(dir_data, 'DS_test.csv')


# 讀取檔案
app_train = pd.read_csv(f_app_train, header=None)
app_train_label = pd.read_csv(f_app_train_label, header=None)
app_test = pd.read_csv(f_app_test, header=None)

In [13]:
app_train

0         1         2         3          4         5         6   \
0    0.299403 -1.226624  1.498425 -1.176150   5.289853  0.208297  2.404498   
1   -1.174176  0.332157  0.949919 -1.285328   2.199061 -0.151268 -0.427039   
2    1.192222 -0.414371  0.067054 -2.233568   3.658881  0.089007  0.203439   
3    1.573270 -0.580318 -0.866332 -0.603812   3.125716  0.870321 -0.161992   
4   -0.613071 -0.644204  1.112558 -0.032397   3.490142 -0.011935  1.443521   
..        ...       ...       ...       ...        ...       ...       ...   
995 -0.310429  0.826811 -0.952245  0.768850   1.877520  1.320646  1.944609   
996 -1.853879  0.246726  0.459921 -2.074267   7.599220 -0.138355 -4.501900   
997  0.912748 -1.734039 -1.047035  0.217573  13.457812  0.162771 -2.250521   
998  2.439780 -0.735511 -0.902426  1.365036 -10.430299 -0.856859  2.686474   
999  0.228994 -0.085453  0.876582  1.057401  -1.404015 -1.091965  0.639176   

           7         8         9   ...        30        31        32  \
0    1.594506 -0.051608  0.663234  ... -0.850465 -0.622990 -1.833057   
1    2.619246 -0.765884 -0.093780  ... -0.819750  0.012037  2.038836   
2   -4.219054 -1.184919 -1.240310  ... -0.604501  0.750054 -3.360521   
3    4.499666  1.038741 -1.092716  ...  1.022959  1.275598 -3.480110   
4   -4.290282 -1.761308  0.807652  ...  0.513906 -1.803473  0.518579   
..        ...       ...       ...  ...       ...       ...       ...   
995  1.191420 -0.127724  0.070937  ... -0.600411 -0.383792  0.745596   
996  0.630634 -1.590533 -1.112949  ...  0.361736  0.240052 -0.856196   
997  2.216161 -0.378326  0.642114  ...  1.195896 -1.073806 -2.754369   
998  0.292035  0.585388 -0.876965  ...  2.262326 -0.039488  0.773876   
999  0.701332 -0.906577 -0.390940  ...  0.471415  1.024757 -1.796571   

           33        34        35        36        37        38        39  
0    0.293024  3.552681  0.717611  3.305972 -2.715559 -2.682409  0.101050  
1    0.468579 -0.517657  0.422326  0.803699  1.213219  1.382932 -1.817761  
2    0.856988 -2.751451 -1.582735  1.672246  0.656438 -0.932473  2.987436  
3   -1.065252  2.153133  1.563539  2.767117  0.215748  0.619645  1.883397  
4   -0.205029 -4.744566 -1.520015  1.830651  0.870772 -1.894609  0.408332  
..        ...       ...       ...       ...       ...       ...       ...  
995 -0.698598 -2.729937 -0.431535  0.372873  1.019092 -2.672811 -0.295141  
996 -0.072481 -2.935896  0.582411 -2.613407  0.036687  2.809310  4.412567  
997  1.814864 -4.190105 -1.116441 -2.100125  0.061513  0.895536  0.813686  
998 -0.916066  2.604827 -0.649874 -3.423674  0.229748 -2.311088 -3.422217  
999  0.603161  0.862705  0.747234  3.275681  0.400372 -3.431031  2.370080  

[1000 rows x 40 columns]

In [14]:
print(app_train.shape)
print(app_train_label.shape)
print(app_test.shape)

(1000, 40)
(1000, 1)
(9000, 40)


In [16]:
app_train.describe()

0            1            2            3            4   \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean      0.025596    -0.024526    -0.024088    -0.002271     1.092329   
std       1.008282     1.016298     0.979109     0.970575     4.538834   
min      -3.365711    -3.492086    -2.695602    -3.460471   -16.421901   
25%      -0.669010    -0.693937    -0.698830    -0.617557    -1.801997   
50%       0.027895    -0.033194     0.008145     0.002327     0.862818   
75%       0.762520     0.682753     0.661434     0.640743     3.843172   
max       3.326246     3.583870     2.546507     3.088738    17.565345   

                5            6            7            8            9   ...  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000  ...   
mean     -0.006250     0.497342    -0.037883     0.026391    -0.003597  ...   
std       0.989128     2.118819     2.232256     1.001064     1.013520  ...   
min      -3.041250    -7.224761    -6.509084    -3.145588    -2.749812  ...   
25%      -0.732265    -0.838619    -1.604037    -0.677562    -0.682220  ...   
50%       0.027041     0.582321     0.018809     0.022092    -0.036110  ...   
75%       0.671456     1.913664     1.438304     0.741310     0.665364  ...   
max       3.102997     7.592666     7.130097     3.145258     3.919426  ...   

                30           31           32           33           34  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean      0.030651     0.022951    -0.542491    -0.011608    -0.483507   
std       1.011645     1.001375     2.239939     1.022456     2.121281   
min      -3.379194    -2.971125    -7.840890    -2.999564    -7.124105   
25%      -0.659457    -0.696032    -2.121943    -0.664550    -1.879247   
50%       0.049416     0.049778    -0.568262    -0.028097    -0.493575   
75%       0.747031     0.699917     0.939348     0.651374     1.005795   
max       2.844792     3.688047     7.160379     3.353631     6.005818   

                35           36           37           38           39  
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000  
mean      0.033371     0.567185     0.006849    -0.892659     0.609451  
std       1.007044     2.227876     0.997635     2.022022     2.045439  
min      -2.952358    -5.452254    -3.473913    -8.051722    -7.799086  
25%      -0.642861    -1.059786    -0.691162    -2.220126    -0.565041  
50%       0.037732     0.455474     0.038284    -0.855470     0.779944  
75%       0.691800     2.122157     0.693535     0.388698     1.992193  
max       3.420561     6.603499     3.492548     5.774120     6.803984  

[8 rows x 40 columns]

In [21]:
from sklearn.preprocessing import MinMaxScaler

# 縮放器 : 設定特徵縮放到 0~1 區間
scaler = MinMaxScaler(feature_range = (0, 1))

# 縮放器載入 train 的上下限, 對 train, test 進行縮放轉換
scaler.fit(app_train)
train = scaler.transform(app_train)
test = scaler.transform(app_test)
print(train.shape)
print(test.shape)

(1000, 40)
(9000, 40)


In [40]:
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.model_selection import train_test_split

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(train, np.ravel(app_train_label), test_size=0.25)
print(x_train.shape)
print(y_train.shape)

(750, 40)
(750,)


In [51]:
# Model: 隨機森林
# n_estimators=10, #決策樹的數量
# max_features="auto", #選取的特徵數量 The number of features to consider when looking for the best split: 
#                      If “auto”, then max_features=sqrt(n_features)
# 建立模型 (使用 20 顆樹，每棵樹的最大深度為 4)
clf = RandomForestClassifier(n_estimators=50, max_depth=4, max_features='auto')

# 訓練模型
clf.fit(x_train, y_train)

# 預測測試集
y_pred = clf.predict(x_test)
y_pred

array([1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1], dtype=int64)

In [52]:
acc = metrics.accuracy_score(y_test, y_pred)
print("Accuracy: ", acc)

Accuracy:  0.86


In [55]:
#multiclass多分類評分: 須加上average參數 average{'micro', 'macro', 'samples','weighted', 'binary'} or None, default='binary'
f1 = metrics.f1_score(y_test, y_pred) # 使用 F1-Score 評估: If average=None, the scores for each class are returned.
precision = metrics.precision_score(y_test, y_pred) # 使用 Precision 評估
recall  = metrics.recall_score(y_test, y_pred) # 使用 recall 評估
print("F1-Score: ", f1) 
print("Precision: ", precision)
print("Recall: ", recall)

F1-Score:  0.8582995951417004
Precision:  0.8833333333333333
Recall:  0.8346456692913385


In [56]:
from sklearn.ensemble import GradientBoostingClassifier

In [59]:
# Model: 梯度提升機
# 建立模型
clf = GradientBoostingClassifier()

# 訓練模型
clf.fit(x_train, y_train)

# 預測測試集
y_pred = clf.predict(x_test)
y_pred

array([1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0], dtype=int64)

In [60]:
acc = metrics.accuracy_score(y_test, y_pred)
print("Accuracy: ", acc)

Accuracy:  0.896


In [61]:
#multiclass多分類評分: 須加上average參數 average{'micro', 'macro', 'samples','weighted', 'binary'} or None, default='binary'
f1 = metrics.f1_score(y_test, y_pred) # 使用 F1-Score 評估: If average=None, the scores for each class are returned.
precision = metrics.precision_score(y_test, y_pred) # 使用 Precision 評估
recall  = metrics.recall_score(y_test, y_pred) # 使用 recall 評估
print("F1-Score: ", f1) 
print("Precision: ", precision)
print("Recall: ", recall)

F1-Score:  0.8951612903225807
Precision:  0.9173553719008265
Recall:  0.8740157480314961


In [62]:
#以Model: 梯度提升機 訓練 all trainset, 預測testset
# 建立模型
clf = GradientBoostingClassifier()

app_train_label = np.ravel(app_train_label)
# 訓練模型
clf.fit(train, app_train_label)

# 預測測試集
y_pred = clf.predict(test)
y_pred

array([1, 0, 1, ..., 1, 0, 1], dtype=int64)

In [64]:
y_pred.shape

(9000,)

In [78]:
# 計算提交結果
submit = pd.DataFrame(y_pred).reset_index()
submit.columns = ['Id','Solution']
submit['Id'] = submit['Id'] + 1
submit

Id  Solution
0        1         1
1        2         0
2        3         1
3        4         0
4        5         0
...    ...       ...
8995  8996         0
8996  8997         1
8997  8998         1
8998  8999         0
8999  9000         1

[9000 rows x 2 columns]

In [79]:
out_dir = './output/'
f_out = os.path.join(out_dir, 'DataScienceLondon_predict1.csv')
submit.to_csv(f_out, index=False)

<img src="./img/kaggle_DataScienceLondon_2021111901.jpg" >